---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    docker_stack_deploy_name: example
    docker_stack_deploy_state: present
    docker_stack_deploy_root_dir_path: /opt/example
    docker_stack_deploy_root_dir_mode: "0777"
    docker_stack_deploy_root_dir_state: directory
    docker_stack_deploy_root_dir_owner: root
    docker_stack_deploy_root_dir_group: root
    docker_stack_deploy_additional_dirs:
      - path: data
        mode: "0777"
    docker_stack_deploy_template_files:
      - src: test-file.yml.j2
        dest: docker-compose.yml
        mode: "0700"
    docker_stack_deploy_copy_files:
      - src: test-file.html
        dest: data/index.html
        mode: "0770"

  tasks:
    - name: "Include mirceanton.docker_stack_deploy"
      include_role:
        name: "mirceanton.docker_stack_deploy"
